#!/bin/bash

# Version 1.2.1
# Made by: Edgar RP
# Updated: 2025_02_19 (AAAA_MM_DD)
# Script to list show the disk usage in all zfs pools for any device

set -e # To avoid any non-zero output to stop the script
DEV_LOC='DEVICE_TYPE' # Device type can only be a string with 'server', 'proxy' or 'workstation' values
_check_dev "$DEV_LOC" # Checking if the device type is correctly set

#To use this command, it should look like: zfs_disk_activity
if [ "$EUID" -lt 0 ] ; then
    echo "ERROR: It is running with an effective uid negative?"
    exit 1
else
    echo "The disk activity for zfs pool will be shown in 5 seconds. To get out of this view, press 'Ctrl + C'"
    sleep 5
    watch -n1 zpool iostat
    exit 0
fi
